Kov 463 [FEAT] 게시글 로그 분석 api
KEA-Kovengers/Backend pull request #38
Opened 2024-05-28 13:25 UTC by 2sojeong

# 요약
- 블럭 생성자 조회 api
- 블럭 id, 블럭에 참여한 유저 id  조회 api

# 변경사항

# 결과
<img width="1459" alt="image" src="https://github.com/KEA-Kovengers/Backend/assets/118418288/29721e2a-e18f-4908-a973-e814f7dd9792">

# 이슈넘버
- Kov 463

2024-05-29 00:21 UTC, wooing1084 commented on article-service/src/main/java/com/newcord/articleservice/domain/article_version/entity/VersionOperation.java
> +// contorl+tab plz
이게 무슨 말인지

2024-05-29 00:36 UTC, wooing1084 commented on article-service/src/main/java/com/newcord/articleservice/domain/editor/service/EditorComposeServiceImpl.java
> +        Article article = articlesQueryService.findArticleById(postID);
함수 파라미터의 postID랑 article.getId랑 같은거라 이 줄 빼도 될거같습니다

2024-05-29 00:41 UTC, wooing1084 commented on article-service/src/main/java/com/newcord/articleservice/domain/editor/controller/EditorController.java
> +    public ApiResponse<List<EditorLogResponseDTO>> getEditorsLogData(@PathVariable Long postId){
List<DTO>형태 말고 DTO안에 List를 넣어주세여

2024-05-29 00:46 UTC, wooing1084 commented on article-service/src/main/java/com/newcord/articleservice/domain/editor/controller/EditorController.java
> +    public ApiResponse<List<EditorLogResponseDTO>> getEditorsLogData(@PathVariable Long postId){
이 기능은 게시글 상세 페이지에서 특정 유저가 블록에 참여했는지 하이라이트 하는 기능으로 쓸 수 있을거같고, 게시글 분석 그래프를 그릴수 있게 통계내서 반환하는 API가 따로 필요할것같습니다

2024-05-29 00:46 UTC, wooing1084 commented on article-service/src/main/java/com/newcord/articleservice/domain/editor/service/EditorComposeServiceImpl.java
> +        return new ArrayList<>(uniqueResults);
DTO에 hashMap을 바로 입력한건가여.
stream.mapping 메소드 쓰면 객체 변환이 될겁니다

2024-05-29 00:48 UTC, wooing1084 requested changes
메세지 확인해주시고, PR 메인에 response도 첨부해주세요
그리고 editor 도메인에 기능 구현했는데, 가능하면 분석이나 로그라는 이름으로 도메인 새로 만들어서 하는게 좋을것같습니다.

2024-05-29 05:55 UTC, 2sojeong commented on article-service/src/main/java/com/newcord/articleservice/domain/editor/service/EditorComposeServiceImpl.java
> +        return new ArrayList<>(uniqueResults);
이건 모르겠어여 ...

2024-05-30 00:11 UTC, wooing1084 approved these changes
고생하셨습니다

2024-05-30 04:19 UTC, merged