Kov 123 feat/add login
KEA-Kovengers/Backend pull request #5
Opened 2024-04-08 08:19 UTC by somi4219

# 요약
- 로그인 기능 추가

# 변경사항
- 인가 코드 받아서 엑세스 토큰 발급
- 엑세스 토큰으로 사용자 정보 가져옴
- jwt access 토큰/ refresh 토큰 발급

# 결과
<img width="875" alt="스크린샷 2024-04-08 오후 5 16 36" src="https://github.com/KEA-Kovengers/Backend/assets/125250173/7421d272-15d2-4876-ba12-351c13e8f503">
<img width="895" alt="스크린샷 2024-04-08 오후 5 16 45" src="https://github.com/KEA-Kovengers/Backend/assets/125250173/417e591e-8c4d-4b5e-8d8a-d32d950af67f">

# 이슈넘버
- Kov 123

2024-04-08 16:14 UTC, wooing1084 requested changes
코멘트 확인해주세요

2024-04-08 16:14 UTC, wooing1084 commented on user-service/src/main/java/com/newcord/userservice/auth/api/KakaoController.java
> +
Controller에는 가능한 서비스 로직이 들어가지 않도록 Servcie로 빼주세요

2024-04-08 16:14 UTC, wooing1084 commented on user-service/src/main/java/com/newcord/userservice/user/domain/Users.java
> +@Getter @Setter
@Setter는 가능한 사용하지 말아주세요
Set이 필요한 변수만 따로 메소드를 만들어주고 만들때 함수명을 의도가 명확하게 지어주세요

2024-04-10 05:29 UTC, hspark-1 commented on user-service/src/main/java/com/newcord/userservice/auth/api/KakaoController.java
> +
동의

2024-04-10 05:29 UTC, hspark-1 commented on user-service/src/main/resources/application.yml
> +  secret: 01254cd9f9f67bab5529f1d210a20d93eab0aa9d09d681e3b201b36a4069fd6b
jwt 시크릿키 여기 포함되어도 되나요

2024-04-10 05:29 UTC, hspark-1 commented on user-service/src/main/resources/static/index.html
> +<a href="https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=a61af306bdb89fc8bbbaced44fb4fef0&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fapi%2Fauth%2Flogin">
test용인가요

2024-04-10 05:59 UTC, wooing1084 approved these changes

2024-04-10 05:59 UTC, wooing1084 commented on user-service/src/main/resources/application.yml
> +  secret: 01254cd9f9f67bab5529f1d210a20d93eab0aa9d09d681e3b201b36a4069fd6b
동의

2024-04-11 00:13 UTC, 2sojeong approved these changes

2024-04-11 00:14 UTC, somi4219 commented on user-service/src/main/resources/application.yml
> +  secret: 01254cd9f9f67bab5529f1d210a20d93eab0aa9d09d681e3b201b36a4069fd6b
보감

2024-04-11 00:26 UTC, merged